-- SCRIPT PENYESUAIAN TABEL AUTHENTICATION & USERS SUPABASE (UNIKA.IN)

-- 1. BUAT TABEL MASTER USERS
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL CHECK (role IN ('MAHASISWA', 'DPL', 'MITRA', 'ADMIN_PRODI')),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. TAMBAHKAN KOLOM user_id PADA TABEL ENTITAS (IF NOT EXISTS)
ALTER TABLE mahasiswa ADD COLUMN IF NOT EXISTS user_id INT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE dosen_pembimbing ADD COLUMN IF NOT EXISTS user_id INT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mitra_industri ADD COLUMN IF NOT EXISTS user_id INT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE admin_kaprodi ADD COLUMN IF NOT EXISTS user_id INT REFERENCES users(id) ON DELETE CASCADE;

-- 3. TAMBAHKAN KOLOM FORMULIR FAKULTAS PADA pengajuan_magang (RECREATE GOOGLE FORM)
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS nama_instansi VARCHAR(150);
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS alamat_instansi TEXT;
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS tujuan_surat VARCHAR(150);
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS semester INT;
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS tahun_akademik VARCHAR(20);
ALTER TABLE pengajuan_magang ADD COLUMN IF NOT EXISTS jenis_surat_fakultas VARCHAR(100);

-- 4. INDEX UNTUK KECEPATAN AUTHENTICATION
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
